from tkinter import *
from tkinter import filedialog
import pymysql
from dataBase import *
DataBase=DataBase()
root=Tk()
root.config( width=300, height=300)
root.resizable(0,0)
root.iconbitmap("volante.ico")
root.config(bg="#2E2E2E")
#miImagen=PhotoImage(file="fondo.png")
Label(root, text="Bienvenidos/as a conductor designado", bg="#2E2E2E",fg="#58FAF4", font="Times 16").grid(row=0, columnspan=5)
#Label(root, text="", bg="#2E2E2E").pack()
#----------------------en esta parte esta inicar sesion y registrarse-----------
inicioMenu=Frame(root, bg="#2E2E2E")
inicioMenu.grid(row=1, column=0)
registroMenu=Frame(root, bg="#2E2E2E")
registroMenu.grid(row=1, column=0)
#-----------menu dentro del menu registro------------
conductorMenu=Frame(root, bg="#2E2E2E")
conductorMenu.grid(row=1, column=0)
comercioMenu=Frame(root, bg="#2E2E2E")
comercioMenu.grid(row=1, column=0)
#------------iniciar sesion Frame--------
inciarSesionFrame=Frame(root, bg="#2E2E2E")
inciarSesionFrame.grid(row=1, column=0)
varOpcion=IntVar()
genero=""
etiqueta=Label(conductorMenu)
foto=""
def abreFichero():
    global foto
    fichero=filedialog.askopenfilename(title="abrir", initialdir="C:", filetypes=(("ficheros de png", "*.png"),
    ("ficheros de jpg", "*.jpg")))
    foto=fichero
    print(fichero)
def imprimir():
    global genero
    if varOpcion.get()==1:
        genero="Masculino"
        etiqueta.config(text="Masculino", bg="#2E2E2E",fg="#58FAF4", font="Times 12")
    else:
        genero="Femenino"
        etiqueta.config(text="Femenino", bg="#2E2E2E",fg="#58FAF4", font="Times 12")
def formulario_conductor():
    global genero
    global foto
    def enviarDatos():
        DataBase.insertarConductor(miIdConductor.get(),miNombreConductor.get(),miApellidoConductor.get(),
        miPassConductor.get(),miEdadConductor.get(),miProvinciaConductor.get(),miLocalidadConductor.get(),
        miDomilicioConductor.get(),genero, foto)
    miIdConductor=StringVar()
    miNombreConductor=StringVar()
    miApellidoConductor=StringVar()
    miEdadConductor=IntVar()
    miPassConductor=StringVar()
    miProvinciaConductor=StringVar()
    miLocalidadConductor=StringVar()
    miDomilicioConductor=StringVar()
    cuentaConductor=Label(conductorMenu, text="cuenta: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    cuentaConductor.grid(row=0, column=0)
    cuentaConductorEntry=Entry(conductorMenu, textvariable=miIdConductor)
    cuentaConductorEntry.grid(row=0, column=1, ipady=2, ipadx=18, pady=2)
    nombreConductor=Label(conductorMenu, text="Nombre: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    nombreConductor.grid(row=0, column=2, ipady=2)
    nombreConductorEntry=Entry(conductorMenu, textvariable=miNombreConductor)
    nombreConductorEntry.grid(row=0, column=3, ipady=2, pady=2)
    apellidoConductor=Label(conductorMenu, text="Apellido: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    apellidoConductor.grid(row=1, column=0, ipady=2)
    apellidoConductorEntry=Entry(conductorMenu, textvariable=miApellidoConductor)
    apellidoConductorEntry.grid(row=1, column=1, ipady=2, ipadx=18, pady=2)
    contrasegnaConductor=Label(conductorMenu, text="contraseña: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    contrasegnaConductor.grid(row=1, column=2)
    contrasegnaConductorEntry=Entry(conductorMenu, show="*", textvariable=miPassConductor)
    contrasegnaConductorEntry.grid(row=1, column=3, ipady=2)
    edadConductor=Label(conductorMenu, text="Edad: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    edadConductor.grid(row=2, column=0)
    edadConductorEntry=Entry(conductorMenu, textvariable=miEdadConductor)
    edadConductorEntry.grid(row=2, column=1, ipady=2, ipadx=18, pady=2)
    provinciaConductor=Label(conductorMenu, text="Provincia: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    provinciaConductor.grid(row=2, column=2)
    provinciaConductoEntry=Entry(conductorMenu, textvariable=miProvinciaConductor)
    provinciaConductoEntry.grid(row=2, column=3, ipady=2)
    localidadConductor=Label(conductorMenu, text="Localidad: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    localidadConductor.grid(row=3, column=0)
    localidadConductoEntry=Entry(conductorMenu, textvariable=miLocalidadConductor)
    localidadConductoEntry.grid(row=3, column=1, ipady=2, ipadx=18, pady=2)
    domicilioConductor=Label(conductorMenu, text="Calle/dpto/piso: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    domicilioConductor.grid(row=3, column=2)
    domicilioConductoEntry=Entry(conductorMenu, textvariable=miDomilicioConductor)
    domicilioConductoEntry.grid(row=3, column=3, ipady=2)
    Radiobutton(conductorMenu, text="masculino", variable=varOpcion, value=1, bg="#2E2E2E",fg="#58FAF4", font="Times 13", command=imprimir).grid(row=4, column=1)
    Radiobutton(conductorMenu, text="femenino", variable=varOpcion, value=2, bg="#2E2E2E",fg="#58FAF4", font="Times 13", command=imprimir).grid(row=4, column=2)
    etiqueta.grid(row=5, column=1)
    Button(conductorMenu, text="Adjuntar Carnet de Conducir", bg="#2E2E2E",fg="#58FAF4", font="Times 10", command=abreFichero).grid(row=5, column=2)
    Button(conductorMenu, text="Enviar Datos", bg="#2E2E2E",fg="#58FAF4", font="Times 10", command=enviarDatos).grid(row=6, column=1, pady=3)
def formulario_comercio():
    global foto
    def enviarDatosComercio():
        DataBase.insertarComercio(miIdComercio.get(),miDniComercio.get(),miNombreComercio.get(),
        miPassComercio.get(),miProvinciaComercio.get(),miLocalidadComercio.get(),miDomilicilioComercio.get(),foto)
    miIdComercio=StringVar()
    miDniComercio=IntVar()
    miNombreComercio=StringVar()
    miPassComercio=StringVar()
    miProvinciaComercio=StringVar()
    miLocalidadComercio=StringVar()
    miDomilicilioComercio=StringVar()
    cuentaComercio=Label(conductorMenu, text="cuenta: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    cuentaComercio.grid(row=0, column=0)
    cuentaComercioEntry=Entry(conductorMenu, textvariable=miIdComercio)
    cuentaComercioEntry.grid(row=0, column=1, ipady=2, ipadx=18, pady=2)
    dniDueñoComercio=Label(conductorMenu, text="DNI del dueño: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    dniDueñoComercio.grid(row=0, column=2)
    dniDueñoComercioEntry=Entry(conductorMenu, textvariable=miDniComercio)
    dniDueñoComercioEntry.grid(row=0, column=3, ipady=2)
    nombreComercio=Label(conductorMenu, text="Nombre del Local: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    nombreComercio.grid(row=1, column=0)
    nombreComercioEntry=Entry(conductorMenu,textvariable=miNombreComercio)
    nombreComercioEntry.grid(row=1, column=1, ipady=2, ipadx=18)
    contrasegnaComercio=Label(conductorMenu, text="contraseña: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    contrasegnaComercio.grid(row=1, column=2)
    contrasegnaComercioEntry=Entry(conductorMenu, show="*", textvariable=miPassComercio)
    contrasegnaComercioEntry.grid(row=1, column=3, ipady=2)
    provinciaComercio=Label(conductorMenu, text="Provincia: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    provinciaComercio.grid(row=2, column=0)
    provinciaComercioEntry=Entry(conductorMenu,textvariable=miProvinciaComercio)
    provinciaComercioEntry.grid(row=2, column=1, ipady=2, ipadx=18, pady=2)
    localidadComercio=Label(conductorMenu, text="Localidad: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    localidadComercio.grid(row=2, column=2)
    localidadComercioEntry=Entry(conductorMenu,textvariable=miLocalidadComercio)
    localidadComercioEntry.grid(row=2, column=3, ipady=2)
    domicilioComercio=Label(conductorMenu, text="Calle/dpto/piso: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    domicilioComercio.grid(row=3, column=0)
    domicilioComercioEntry=Entry(conductorMenu,textvariable=miDomilicilioComercio)
    domicilioComercioEntry.grid(row=3, column=1, ipady=2, ipadx=18, pady=2)
    Button(conductorMenu, text="Adjuntar Copia AFIP", bg="#2E2E2E",fg="#58FAF4", font="Times 10", command=abreFichero).grid(row=4, column=1)
    Button(conductorMenu, text="Enviar Datos", bg="#2E2E2E",fg="#58FAF4", font="Times 10", command=enviarDatosComercio).grid(row=5, column=1, pady=3)
def inicio_de_sesion():
    def verificar(cuenta):
        try:
            DataBase.verificar_user(cuenta, idString.get(), passString.get())
            messagebox.showinfo("BBDD", "se ah accedido con exito")
            cuentaFrame=Frame(root, bg="#2E2E2E", width=400, height=400)
            cuentaFrame.grid(row=1, column=0)
            menuCuenta=Menu(cuentaFrame)
        except:
            messagebox.showwarning("ATENCION!", "id y/o password incorrecto")
    idString=StringVar()
    passString=StringVar()
    cuenta=Label(inciarSesionFrame, text="ID: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    cuenta.grid(row=2, column=0)
    cuentaEntry=Entry(inciarSesionFrame, textvariable=idString)
    cuentaEntry.grid(row=2, column=1, ipady=2.5, pady=3)
    contrasegna=Label(inciarSesionFrame, text="contraseña: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    contrasegna.grid(row=3, column=0)
    contrasegnaEntry=Entry(inciarSesionFrame, show="*", textvariable=passString)
    contrasegnaEntry.grid(row=3, column=1, ipady=2.5, pady=3)
    entrar=Button(inciarSesionFrame, text="Ingresar como conductor", bg="#2E2E2E",fg="#58FAF4", font="Times 12", command=lambda:verificar("conductor"))
    entrar.grid(row=5, column=0, padx=18, pady=5)
    entrar1=Button(inciarSesionFrame, text="Ingresar como comercio", bg="#2E2E2E",fg="#58FAF4", font="Times 12", command=lambda:verificar("comercio"))
    entrar1.grid(row=5, column=1, padx=18)
    espacio=Label(inciarSesionFrame, text="", bg="#2E2E2E")
    espacio.grid(row=6, column=1)
def opcionesRegistro():
    opciones=Label(registroMenu, text="¿Como Desea registrarse?", bg="#2E2E2E",fg="#58FAF4", font="Times 12")
    opciones.grid(row=1, column=1)
    conductor=Button(registroMenu, text="Conductor", width=10, bg="#2E2E2E",fg="#2EFE2E", command=formulario_conductor)
    conductor.grid(row=2, column=1)
    comercio=Button(registroMenu, text="Comercio", width=10, bg="#2E2E2E",fg="#2EFE2E", command=formulario_comercio)
    comercio.grid(row=3, column=1)
iniciarSesion=Button(inicioMenu, text="Iniciar Sesión", width=10, bg="#2E2E2E",fg="#2EFE2E", command=inicio_de_sesion)
iniciarSesion.grid(row=2, column=4, padx=100)
registrarse=Button(inicioMenu, text="Registrarse", width=10, bg="#2E2E2E",fg="#2EFE2E", command=opcionesRegistro)
registrarse.grid(row=3, column=4)
Label(root, text="By: Mauro Sosa, Alexis Fredes", bg="#2E2E2E",fg="#58FAF4", font="Times 10").grid(row=4, columnspan=4)
root.mainloop()
