from tkinter import *
from tkinter import filedialog
root=Tk()
root.config( width=300, height=300)
root.resizable(0,0)
root.iconbitmap("volante.ico")
root.config(bg="#2E2E2E")
miImagen=PhotoImage(file="fondo.png")
Label(root, text="Bienvenidos/as a conductor designado", bg="#2E2E2E",fg="#58FAF4", font="Times 16").grid(row=0, columnspan=5)
#Label(root, text="", bg="#2E2E2E").pack()
#----------------------en esta parte esta inicar sesion y registrarse-----------
inicioMenu=Frame(root, bg="#2E2E2E")
inicioMenu.grid(row=1, column=0)
registroMenu=Frame(root, bg="#2E2E2E")
registroMenu.grid(row=1, column=0)
#-----------menu dentro del menu registro------------
conductorMenu=Frame(root, bg="#2E2E2E")
conductorMenu.grid(row=1, column=0)
comercioMenu=Frame(root, bg="#2E2E2E")
comercioMenu.grid(row=1, column=0)
#------------iniciar sesion Frame--------
inciarSesionFrame=Frame(root, bg="#2E2E2E")
inciarSesionFrame.grid(row=1, column=0)
varOpcion=IntVar()
etiqueta=Label(conductorMenu)
def abreFichero():
    fichero=filedialog.askopenfilename(title="abrir", initialdir="C:", filetypes=(("ficheros de excel", "*.xlsx"),
    ("ficheros de texto", "*.txt"),("todos los fichero","*.*")))
    print(fichero)
def imprimir():
    if varOpcion.get()==1:
        etiqueta.config(text="Has elegido masculino", bg="#2E2E2E",fg="#58FAF4", font="Times 12")
    else:
        etiqueta.config(text="Has elegido femenino", bg="#2E2E2E",fg="#58FAF4", font="Times 12")
def formulario_conductor():
    cuentaConductor=Label(conductorMenu, text="cuenta: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    cuentaConductor.grid(row=0, column=0)
    cuentaConductorEntry=Entry(conductorMenu)
    cuentaConductorEntry.grid(row=0, column=1, ipady=2, ipadx=18, pady=2)
    contrasegnaConductor=Label(conductorMenu, text="contraseña: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    contrasegnaConductor.grid(row=0, column=2)
    contrasegnaConductorEntry=Entry(conductorMenu, show="*")
    contrasegnaConductorEntry.grid(row=0, column=3, ipady=2)
    edadConductor=Label(conductorMenu, text="Edad: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    edadConductor.grid(row=1, column=0)
    edadConductorEntry=Entry(conductorMenu)
    edadConductorEntry.grid(row=1, column=1, ipady=2, ipadx=18, pady=2)
    provinciaConductor=Label(conductorMenu, text="Provincia: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    provinciaConductor.grid(row=1, column=2)
    provinciaConductoEntry=Entry(conductorMenu)
    provinciaConductoEntry.grid(row=1, column=3, ipady=2)
    localidadConductor=Label(conductorMenu, text="Localidad: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    localidadConductor.grid(row=2, column=0)
    localidadConductoEntry=Entry(conductorMenu)
    localidadConductoEntry.grid(row=2, column=1, ipady=2, ipadx=18, pady=2)
    domicilioConductor=Label(conductorMenu, text="Calle/dpto/piso: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    domicilioConductor.grid(row=2, column=2)
    domicilioConductoEntry=Entry(conductorMenu)
    domicilioConductoEntry.grid(row=2, column=3, ipady=2)
    Radiobutton(conductorMenu, text="masculino", variable=varOpcion, value=1, bg="#2E2E2E",fg="#58FAF4", font="Times 13", command=imprimir).grid(row=3, column=1)
    Radiobutton(conductorMenu, text="femenino", variable=varOpcion, value=2, bg="#2E2E2E",fg="#58FAF4", font="Times 13", command=imprimir).grid(row=3, column=2)
    etiqueta.grid(row=4, column=1)
    Button(conductorMenu, text="Adjuntar Carnet de Conducir", bg="#2E2E2E",fg="#58FAF4", font="Times 10", command=abreFichero).grid(row=4, column=2)
    Button(conductorMenu, text="Enviar Datos", bg="#2E2E2E",fg="#58FAF4", font="Times 10").grid(row=5, column=1, pady=3)
def formulario_comercio():
    cuentaComercio=Label(conductorMenu, text="cuenta: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    cuentaComercio.grid(row=0, column=0)
    cuentaComercioEntry=Entry(conductorMenu)
    cuentaComercioEntry.grid(row=0, column=1, ipady=2, ipadx=18, pady=2)
    contrasegnaComercio=Label(conductorMenu, text="contraseña: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    contrasegnaComercio.grid(row=0, column=2)
    contrasegnaComercioEntry=Entry(conductorMenu, show="*")
    contrasegnaComercioEntry.grid(row=0, column=3, ipady=2)
    provinciaComercio=Label(conductorMenu, text="Provincia: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    provinciaComercio.grid(row=1, column=0)
    provinciaComercioEntry=Entry(conductorMenu)
    provinciaComercioEntry.grid(row=1, column=1, ipady=2, ipadx=18, pady=2)
    localidadComercio=Label(conductorMenu, text="Localidad: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    localidadComercio.grid(row=1, column=2)
    localidadComercioEntry=Entry(conductorMenu)
    localidadComercioEntry.grid(row=1, column=3, ipady=2)
    domicilioComercio=Label(conductorMenu, text="Calle/dpto/piso: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    domicilioComercio.grid(row=2, column=0)
    domicilioComercioEntry=Entry(conductorMenu)
    domicilioComercioEntry.grid(row=2, column=1, ipady=2, ipadx=18, pady=2)
    Button(conductorMenu, text="Adjuntar Copia AFIP", bg="#2E2E2E",fg="#58FAF4", font="Times 10", command=abreFichero).grid(row=3, column=1)
    Button(conductorMenu, text="Enviar Datos", bg="#2E2E2E",fg="#58FAF4", font="Times 10").grid(row=4, column=1, pady=3)
def inicio_de_sesion():
    cuenta=Label(inciarSesionFrame, text="ID: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    cuenta.grid(row=2, column=0)
    cuentaEntry=Entry(inciarSesionFrame)
    cuentaEntry.grid(row=2, column=1, ipady=2.5, pady=3)
    contrasegna=Label(inciarSesionFrame, text="contraseña: ", bg="#2E2E2E",fg="#58FAF4", font="Times 13")
    contrasegna.grid(row=3, column=0)
    contrasegnaEntry=Entry(inciarSesionFrame, show="*")
    contrasegnaEntry.grid(row=3, column=1, ipady=2.5, pady=3)
    entrar=Button(inciarSesionFrame, text="Entrar", bg="#2E2E2E",fg="#58FAF4", font="Times 12")
    entrar.grid(row=5, column=0)
    recuperarCuenta=Button(inciarSesionFrame, text="Recuperar Cuenta", bg="#2E2E2E",fg="#58FAF4", font="Times 12")
    recuperarCuenta.grid(row=5, column=1)
    espacio=Label(inciarSesionFrame, text="", bg="#2E2E2E")
    espacio.grid(row=4, column=1)
def opcionesRegistro():
    opciones=Label(registroMenu, text="¿Como Desea registrarse?", bg="#2E2E2E",fg="#58FAF4", font="Times 12")
    opciones.grid(row=1, column=1)
    conductor=Button(registroMenu, text="Conductor", width=10, bg="#2E2E2E",fg="#2EFE2E", command=formulario_conductor)
    conductor.grid(row=2, column=1)
    comercio=Button(registroMenu, text="Comercio", width=10, bg="#2E2E2E",fg="#2EFE2E", command=formulario_comercio)
    comercio.grid(row=3, column=1)
iniciarSesion=Button(inicioMenu, text="Iniciar Sesión", width=10, bg="#2E2E2E",fg="#2EFE2E", command=inicio_de_sesion)
iniciarSesion.grid(row=2, column=4, padx=100)
registrarse=Button(inicioMenu, text="Registrarse", width=10, bg="#2E2E2E",fg="#2EFE2E", command=opcionesRegistro)
registrarse.grid(row=3, column=4)
#Label(root, text="", bg="#2E2E2E").grid(row=0, columnspan=0)
Label(root, text="By: Mauro Sosa, Alexis Fredes", bg="#2E2E2E",fg="#58FAF4", font="Times 10").grid(row=4, columnspan=4)
root.mainloop()
